name: On unlabeled issue

on:
  issues:
     types:
       - unlabeled

jobs:
  ensure_column:
    name: "📍 Assigned or FirstTimeCodeContribution"
    if: ${{ (github.event.label.name == '📍 Assigned' || github.event.label.name == 'FirstTimeCodeContribution') && github.repository_owner == 'JabRef' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Move Issue to "Free to take" Column in "Candidates for University Projects"
        uses: koppor/github-action-move-issues@fix-35
        with:
          github-token: ${{ secrets.GH_TOKEN_ACTION_MOVE_ISSUE }}
          project-url: "https://github.com/orgs/JabRef/projects/3"
          target-labels: "📍 Assigned"
          target-column: "Assigned"
          ignored-columns: ""
          default-column: "Free to take"
          skip-if-not-in-project: true
      - name: Move Issue to "Free to take" Column in "Good First Issues"
        uses: koppor/github-action-move-issues@fix-35
        with:
          github-token: ${{ secrets.GH_TOKEN_ACTION_MOVE_ISSUE }}
          project-url: "https://github.com/orgs/JabRef/projects/5"
          target-labels: "📍 Assigned"
          target-column: "Assigned"
          ignored-columns: ""
          default-column: "Free to take"
          skip-if-not-in-project: true
