name: On PR labeled

on:
  pull_request:
     types:
       - labeled

jobs:
  automerge:
    name: Auto Merge
    if: >
      github.event.label.name == 'automerge' &&
      github.repository == 'JabRef/jabref' &&
      github.event.pull_request.head.repo.full_name == 'JabRef/jabref'
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN_JABREF_MACHINE_PR_APPROVE}}
      - name: Merge PR
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN_UPDATE_GRADLE_WRAPPER}}
  wisdom:
    name: Wisdom
    if: >
      github.event.label.name == 'dev: wisdom' &&
      github.repository == 'JabRef/jabref'
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: >
            👋 Hey, looks like you’re eager to work on this issue—great! 🎉
            It also looks like you skipped reading our [CONTRIBUTING.md](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md), which explains exactly how to participate. No worries, it happens to the best of us.
            Give it a read, and you’ll discover the ancient wisdom of assigning issues to yourself. Trust me, it’s worth it. 🚀
          comment-tag:
            wisdom
          mode: recreate
